version: '3.8'

networks:
  sw_network:
    driver: bridge

services:
  app:
    build: .
    container_name: smart-wallet-web
    image: smartwalletweb:latest
    networks:
      - sw_network
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
